export const wamList = [
  "Orally",
  "Sublingually",
  "Nasally",
  "Topically",
  "Intravenously",
]

export const intakeTimeList = [
  "00:00",
  "01:00",
  "02:00",
  // "03:00",
  // "04:00",
  // "05:00",
  // "06:00",
  // "07:00",
  // "08:00",
  // "09:00",
  // "10:00",
  // "11:00",
  // "12:00",
  // "13:00",
  // "14:00",
  // "15:00",
  // "16:00",
  // "17:00",
  // "18:00",
  // "19:00",
  // "20:00",
  // "21:00",
  // "22:00",
  // "23:00",
]

export const medicineList = [
  { name: "Paracetamol", wamId: 0 },
  // { name: "Ibuprofen", wamId: 0 },
  // { name: "Amoxicillin", wamId: 0 },
  // { name: "Metformin", wamId: 0 },
  // { name: "Atorvastatin", wamId: 0 },
  // { name: "Lisinopril", wamId: 0 },
  // { name: "Omeprazole", wamId: 0 },
  // { name: "Amlodipine", wamId: 0 },
  // { name: "Losartan", wamId: 0 },
  // { name: "Sertraline", wamId: 0 },
  // { name: "Nitroglycerin", wamId: 1 },
  // { name: "Buprenorphine", wamId: 1 },
  // { name: "Cyanocobalamin (Vitamin B12)", wamId: 1 },
  // { name: "Lorazepam", wamId: 1 },
  // { name: "Clonazepam", wamId: 1 },
  { name: "Zolpidem", wamId: 1 },
  // { name: "Melatonin", wamId: 1 },
  // { name: "Estradiol", wamId: 1 },
  // { name: "Isosorbide dinitrate", wamId: 1 },
  // { name: "Ondansetron", wamId: 1 },
  // { name: "Fluticasone (Flonase)", wamId: 2 },
  // { name: "Oxymetazoline (Afrin)", wamId: 2 },
  // { name: "Sumatriptan (Imitrex)", wamId: 2 },
  // { name: "Naloxone (Narcan)", wamId: 2 },
  // { name: "Desmopressin (DDAVP)", wamId: 2 },
  { name: "Ketamine", wamId: 2 },
  // { name: "Mometasone (Nasonex)", wamId: 2 },
  // { name: "Ciclesonide (Zetonna)", wamId: 2 },
  // { name: "Calcitonin (Miacalcin)", wamId: 2 },
  // { name: "Nicotine Nasal Spray", wamId: 2 },
  // { name: "Hydrocortisone cream", wamId: 3 },
  // { name: "Diclofenac gel", wamId: 3 },
  { name: "Clotrimazole cream", wamId: 3 },
  // { name: "Benzoyl peroxide gel", wamId: 3 },
  // { name: "Neosporin ointment", wamId: 3 },
  // { name: "Mupirocin ointment", wamId: 3 },
  // { name: "Capzasin (Capsaicin)", wamId: 3 },
  // { name: "Povidone-iodine (Betadine)", wamId: 3 },
  // { name: "Lidocaine patch", wamId: 3 },
  // { name: "Ketoconazole shampoo", wamId: 3 },
  // { name: "Morphine", wamId: 4 },
  // { name: "Vancomycin", wamId: 4 },
  // { name: "Dexamethasone", wamId: 4 },
  // { name: "Furosemide", wamId: 4 },
  // { name: "Ceftriaxone", wamId: 4 },
  // { name: "Heparin", wamId: 4 },
  // { name: "Magnesium sulfate", wamId: 4 },
  // { name: "Midazolam", wamId: 4 },
  // { name: "Amiodarone", wamId: 4 },
  { name: "Norepinephrine", wamId: 4 },
]
